### ISSUE TITLE
Loading LPE File Related Bugs

### ISSUE THREAD

**Issue by liamortiz** [unsettledgames/pixel-editor#23]
## Use this to keep track of LPE loading issues

- Can't use any tools after loading LPE file, except panning
- Loading LPE file directly from homepage does not fix the panning issue
- Loading LPE file from homepage has a different route in the code, compared to loading while already in a drawing
- Undo and redo won't work after loading LPE file

## Theories

- There's a layer mix up, currently `layers` is a global array with 5 default layers
- Setting `lastMouseClickPos=[0,0]` & manually getting `cursorLocation` inside the pan tool without using the getCursorPosition function, fixes panning.

**Comment by unsettledgames** [comment]
Apparently the layer that is selected to be the currentLayer after a file has been loaded is the wrong one and still refers to the one that is deleted on startup. I'll have a further look, but I think this is the reason why tools and the other elements don't work because when manually selecting the new layer, the editor works correctly.

**Comment by unsettledgames** [comment]
The issue seems to be fixed in 452551907120bbf071bec2c984417423600ac14c
